source 'https://rubygems.org'

gem 'rails', '4.0.1'

gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'pry-rails'
gem 'sass-rails', '~> 4.0.0'
gem 'sqlite3'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

gem 'launchkey', path: '../..'


group :test do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'nyan-cat-formatter'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'webmock'
end

group :development, :test do
  gem 'dotenv-rails'
  gem 'factory_girl_rails'
  gem 'rspec-rails'
end

group :development do
  gem 'spring'
  gem 'spring-commands-rspec', require: false

  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-livereload'
  gem 'guard-pow'
  gem 'guard-rspec'
  gem 'rb-fsevent', require: false
  gem 'rb-inotify', require: false
  gem 'terminal-notifier-guard'
end
